method: bayes
metric:
  name: val_mse
  goal: minimize
parameters:
  learning_rate:
    values: [0.001, 0.0005, 0.0001]
  hidden_channels:
    values: [32, 64, 128]
  num_layers:
    values: [2, 3, 4]
  batch_size:
    values: [16, 32, 64]