sweep_config = {
    'method': 'bayes',  # z.B. 'grid', 'random', oder 'bayes'
    'metric': {
      'name': 'val_mse',   # Metrik, nach der optimiert wird (Val Loss o.ä.)
      'goal': 'minimize'
    },
    'parameters': {
        'learning_rate': {
            'values': [0.001, 0.0005, 0.0001]   # verschiedene LR
        },
        'hidden_channels': {
            'values': [32, 64, 128]            # verschiedene Hidden Größen
        },
        'num_layers': {
            'values': [2, 3, 4]                # verschiedene Anzahl Layer
        },
        'batch_size': {
            'values': [16, 32, 64]
        },
        # Weitere Hyperparameter können ergänzt werden
    }
}